### PR TITLE
Resolve Broccoli deprecation warnings

### PR DESCRIPTION
**Pull request by lsg-braymon**
1. Remove dependency from `broccoli-webfont` since it is no longer active
    * https://github.com/sunflowerdeath/broccoli-webfont
    * Copy implementation from `broccoli-webfont` into this project
1. Use newer `broccoli-caching-writer` to resolve deprecation warnings

### CODE REVIEW

**Comment by ghost** [comment]
This looks great!

Is the build failure above because the CI isn't setup to run on our fork?

**Comment by lsg-braymon** [comment]
@lsg-richard Thanks for the heads up. It was due to the Node version in Travis config that is originally set to 4 and newer dependencies require minimum of Node 6. Ember-CLI has removed Node v4 in their test suite: https://github.com/ember-cli/ember-cli/commit/3b79826bdbeaeb032106f8e66f726bf41eb8ff6c#diff-354f30a63fb0907d4ad57269548329e3

**Comment by ghost** [comment]
@lsg-braymon Great, OK let's wait for an opinion from the maintainer, hopefully they're happy with the update.

**Comment by vitch** [comment]
Thanks - this looks great.

I don't actually have any current use case for this addon but I'm happy to merge this and release a version. Do you see any reason not to publish it as `1.0.0`?

**Comment by lsg-braymon** [comment]
@vitch Thanks! This can be released as `1.0.0`.

**Comment by vitch** [comment]
Thank you! Merged and released as `1.0.0`

**Pull request merged**
